---

- name: Create new MySQL root user password
  command: >
    pwmake 256
  register: mysql_root_password
  changed_when: false
  no_log: true

- name: Determine if root user password is set
  command: >
    mysql -u root -e 'quit'
  changed_when: false
  register: mysql_root_password_set

- name: Update MySQL root user password
  command: >
    mysql -u root
    -e 'ALTER USER "root"@"localhost" IDENTIFIED BY "{{ mysql_root_password.stdout }}";'
  changed_when: true
  when: mysql_root_password_set.rc == 0
  no_log: true

- name: Put in place root user .my.cnf file
  template:
    src: root_my_cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'
  when: mysql_root_password_set.rc == 0
