---

- name: Install MySQL Community Packages
  yum:
    name: mysql-community-server
    state: present
    disable_excludes: all
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

- name: Install RHEL MySQL Packages
  yum:
    name: mysql-server
    state: present
    disable_excludes: all
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"

- name: Install MySQL python module
  yum:
    name: python3-mysql
    state: present

- name: Ensure password generate tool is installed
  yum:
    name: libpwquality
    state: present

- name: Enable and Start MySQL services
  service:
    name: mysqld
    enabled: yes
    state: started
