---

- name: Install MySQL Packages
  yum:
    name: mysql-community-server
    state: present
    disable_excludes: all

- name: Install MySQL python module
  yum:
    name: python3-mysql
    state: present

- name: Ensure password generate tool is installed
  yum:
    name: libpwquality
    state: present

- name: Enable and Start MySQL services
  service:
    name: mysqld
    enabled: yes
    state: started
