---

- name: Set-up the MySQL Yum Repoistory on the system
  import_tasks: setup_mysql_yumrepo.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

- name: Install the MySQL server on the system
  import_tasks: install_mysql_server.yml
  tags:
    - install-mysqlserver

- name: Configure the MySQL Community server
  import_tasks: "config_mysql{{ mysql_installrepo_version }}.yml"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

- name: Configure the RHEL MySQL server
  import_tasks: "config_mysqld.yml"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"

- name: Create MySQL Databases
  import_tasks: create_mysql_databases.yml
  when: mysql_databases is defined
  tags:
    - create-databases

- name: Create MySQL Users
  import_tasks: create_mysql_users.yml
  when: mysql_users is defined
  tags:
    - create-users