---

- name: Set-up the MySQL Yum Repoistory on the system
  include_tasks: setup_mysql_yumrepo.yml

- name: Install the MySQL server on the system
  include_tasks: install_mysql_server.yml

- name: Configure the MySQL server
  include_tasks: "config_mysql{{ mysql_installrepo_version }}.yml"

# This allows for making the {{ project_name }}_{{ env_name }}.yml vars file optional.
# If this vars file is _not_ included in the role, the variables should be defined
# elsehwere - e.g. in the playbook file
- name: Determine if the project-specific vars file exists
  local_action:
    module: stat
    path: "{{ role_path }}/vars/{{ project_name }}_{{ env_name }}.yml"
  become: False
  register: project_vars_file

- name: Set Database and User Variables
  include_vars: "{{ project_name }}_{{ env_name }}.yml"
  when: project_vars_file.stat.exists
  no_log: True

- name: Create MySQL Databases
  include_tasks: create_mysql_databases.yml
  when: mysql_databases is defined

- name: Create MySQL Users
  include_tasks: create_mysql_users.yml
  when: mysql_users is defined
