---

- name: Set-up the MySQL Yum Repoistory on the system
  include_tasks: setup_mysql_yumrepo.yml

- name: Install the MySQL server on the system
  include_tasks: install_mysql_server.yml

- name: Configure the MySQL server
  include_tasks: "config_mysql{{ mysql_installrepo_version }}.yml"

# NOTE: if you do not use a project vars file, the database and user variables
# must be set in some other way, there are multiple options for doing this
# but you'll need to use them, and they may not be as secure as using a
# project vars file

- name: Determine if optional project vars file exists
  local_action: stat path="{{ project_name }}_{{ env_name }}.yml"
  register: project_vars_file

- name: Set Database and User Variables
  include_vars: "{{ project_name }}_{{ env_name }}.yml"
  when: project_vars_file.stat.exists
  no_log: True

- name: Create MySQL Databases
  include_tasks: create_mysql_databases.yml
  when: mysql_databases is defined

- name: Create MySQL Users
  include_tasks: create_mysql_users.yml
  when: mysql_users is defined
